baseURL = "https://shorinbonsai.github.io/"
languageCode = "en-us"
theme = "anatole"
enableEmoji = true

[params]
title = "A Little Bit Rusty"
author = "James Sargant"
description = "A Digital Home"

